<h2>Main administrative tools</h2>
<p>
 <a href="?c=m">Manual update</a><br/>
 Tool that updates the manual from the XML files on the server.<br/>
 <b>Warning</b>: this tool is very resource-consuming; please don't run it unless you have a good reason to.
</p>
<p>
 <a href="?c=a">Account management</a><br/>
 This tool allows operations such as changing an account's email address or password.
</p>
<p>
 <a href="?c=k">Request player kick</a><br/>
 Request that a player be banned from the game. Another admin will have to validate your request.<br/>
 <a href="?c=kl">Manage kicks</a><br/>
 Display the list of pending, accepted and rejected kick requests, and validate pending requests.
</p>
<p>
 <u>Link management:</u> <a href="?c=lk">Links &amp; categories</a> - <a href='?c=lkr'>Reports</a> - <a href='?c=lks'>Submissions</a><br/>
 Different tools to manage the main page's links.
</p>

<h2>Beta 5 administrative tools</h2>
<p>
 <a href="?c=p">Planet names</a><br/>
 Planet names moderation tools to spot planets with insulting or "politically incorrect" names.
</p>
<p>
 <a href="?c=s">Admin spam</a><br/>
 Sends a message to all players.
</p>
