<?
include("menu.en.inc");
$this->title = "About Legacy Worlds";
$this->addStylesheet('text');
$this->startContents();
?>
<h1>About LegacyWorlds</h1>
<p>
 Legacy Worlds is an online multiplayer intergalactic war game.
</p>
<p>
 Your goal as a player: build up an empire and defeat the other players.
</p>
<p>
 How to achieve that: through technological research, alliances with other players and of course conquests.
</p>
<p>
 <a href="http://www.deepclone.com/">DeepClone Development</a> is proud to introduce this new version,
 Legacy Worlds Public Beta 5. It has been rewritten from scratch since the previous version and keeps evolving as bugs
 are fixed and features are added.
</p>

<h1>Online Games Directories</h1>
<p>
 Legacy Worlds Beta 5 is listed on the following online games directories:
</p>
<ul>
 <li><a href="http://www.rpg.sg">RPG.SG</a>: <a href="http://www.rpg.sg/profile/195/Legacy-Worlds">here</a></li>
 <li><a href="http://www.mpogd.com/">Multiplayer Online Games Directory</a>: <a href="http://www.mpogd.com/games/game.asp?ID=3499">here</a></li>
 <li><a href="http://www.free-games.com.au">Free Games</a>: <a href="http://www.free-games.com.au/Detailed/1851.html">here</a></li>
 <li><a href="http://www.sweetonlinegames.com">Sweet Online Games</a>: <a href="http://www.sweetonlinegames.com/view/549">here</a></li>
</ul>
<p>
 Please take the time to vote for Legacy Worlds on these sites, as it means more players, and therefore more fun...
</p>

<h1 id="othergames">Other DeepClone Development games</h1>
<p>
 <a href="http://www.gpmanagerpro.com">GP Manager Pro</a> is DeepClone's latest project, a game
 in which you play as the manager of a Grand Prix team.
</p>
<? $this->endContents(); ?>
