<?
$this->title = "Please contribute";
$this->addStylesheet('annoy');
$this->addScript('annoy');
?>
<div id="aframe">
 <h1>Please contribute to LegacyWorlds</h1>
 <p>
  You are seeing this page because you have used quite a few server resources.
 </p>
 <p>
  Contributing doesn't mean you have to pay (although it is an option); you can help
  us by reporting bugs or helping us with the Beta 6 development process...
 </p>
 <p>You will be redirected to the Contributions page in</p>
 <h1><span id="redtime"><?=$args['time']?></span>s</h1>
</div>
