<?
include("menu.en.inc");
$this->title = "Credits";
$this->addStylesheet("credits");
$this->startContents();
?>

<div id="gamename">Legacy Worlds</div>
<div id="gameby">A <a href="http://www.deepclone.com">DeepClone Development</a> game</div>

<div class="category">Original concept</div>
<div class="who">El Christoph</div>

<div class="category">Programming &amp; design</div>
<div class="who">TSeeker</div>

<div class="category">Additional programming</div>
<div class="who">Ju</div>
<div class="who">Lord_Omega</div>

<div class="category">Manual</div>
<div class="who">Ju</div>
<div class="who">Sycophant</div>

<div class="category">Administration</div>
<div class="who">Gilgamesh</div>
<div class="who">Ju</div>
<div class="who">Lord_Omega</div>
<div class="who">Sycophant</div>
<div class="who">TSeeker</div>

<div class="category">Tools</div>
<div class="who"><a href="http://www.php.net">PHP</a> - <a href="http://www.perl.com">Perl</a></div>
<div class="who"><a href="http://www.postgresql.org">PostgreSQL</a> - <a href="http://www.vim.org/">VIM</a></div>
<div class="who"><a href="http://www.gimp.org">The Gimp</a> - <a href="http://www.povray.org">POVRay</a></div>

<div class="misc">Thanks to everyone who contributed to the game with various ideas or by reporting bugs...</div>
<div class="misc">Many bottles of beer were harmed during the making of this game.</div>

<? $this->endContents(); ?>
