<? $this->addStylesheet('home'); ?>
<? include('menu.en.inc'); ?>
<div id="gamedesc">
 Legacy Worlds is a free, massively multiplayer, browser-based strategy game.<br/>
 You don't need any plugins to play it, nor do you need to download anything.<br/>
 This game works best with modern browsers such as
 <a title="Firefox" href="http://www.mozilla.com/firefox/">Firefox 2</a>
 or Internet Explorer 7.<br/>
 <b>JavaScript must be enabled to play!</b>
</div>
