<form action="?" onSubmit="return false"><table cellpadding="0" cellspacing="0">
 <tr>
  <td class="pc5">&nbsp;</td>
  <td class="pc45" id="allies">&nbsp;</td>
  <td class="pc45">
   <h1>Players who trust you</h1>
   <div id="rallies">&nbsp;</div>
  </td>
  <td style="width:5%;vertical-align:top"><a href="manual?p=allies">Help</a></td>
 </tr>
 <tr><td colspan='4'>&nbsp;</td></tr>
 <tr>
  <td class="pc5">&nbsp;</td>
  <td class="pc90" colspan="2">
   <h1>Trusted Allies blacklist</h1>
   <div id="bans">&nbsp;</div>
  </td>
  <td class="pc5">&nbsp;</td>
 </tr>
</table></form>
<div id='alinit' style="display: none; visibility: hidden;"><?=$args?></div>
