<table cellspacing='0' cellpadding='0'>

 <tr><td colspan='3'><table cellspacing='0' cellpadding='0' class='phdr'><tr>
  <td class='pimg' id='pimg'>&nbsp;</td>
  <td class='pttl'><h1 id='plname'> </h1><p id="plactions">&nbsp;</p></td>
  <td class='psel'><form action='?' method='get'>
   <input type='hidden' name='oid' id='oid' value='<?=$args['id']?>' />
   Select planet: <span id='psel'></span> -
   <a href='planets'>Planet list</a> -
   <a href='manual?p=planet'>Help</a>
  </form></td>
 </tr></table></td></tr>
 <tr><td colspan='3'>&nbsp;</td></tr>

 <tr><td colspan='div20'>&nbsp;</td><td id='pldesc'>
 </td><td colspan='div20'>&nbsp;</tr>

</table>
