<?php
$_SESSION['lw_new_game']['do_it_now'] = true;
?>
<br/><br/><br/>
<hr/>
<br/><br/><br/>
<h1 style="text-align:center;font-size:32pt">LAST CHANCE</h1>
<br/><br/>
<form method="GET" action="?">
 <p style="text-align:center;font-size:150%">
  This is your last chance to get back.<br/>
  You are about to create a new LegacyWorlds game, which is no small operation.</br>
  <br/>
  Please, be reasonable and stop now, while you can. Any client crash during the operation could cause the server to be unusable.<br/>
  <br/>
  <input type="submit" name="back" value="Yes, please, take me back, I want the server to live on!" /><br/>
  <br/>
  Ok, you're still reading. That's bad news.<br/>
  Scroll down to access the next step.
 </p>
</form>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<p style="text-align:center"><a href="cg_step0.php">Alea jacta est.</a></p>
